### ISSUE TITLE
Outdated package usage

### ISSUE THREAD

**Issue by ArnolFokam** [devcbuea/dt-collect-web-client#31]
Hey guys, I realized when wondering in [dt-collect-web-client/blob/master/src/components/Header.jsx](https://github.com/devcbuea/dt-collect-web-client/blob/master/src/components/Header.jsx) using the [react-bootstrap documentation](https://react-bootstrap.github.io/) that the version of the react-bootstrap package (0.32.4) we were using wasn't in line with the version on the documentation (^v1.0.0-beta.6) i was reading.
https://github.com/devcbuea/dt-collect-web-client/blob/2dccd327ef4f7adaad8fe46016616924abea7e23/package.json#L7-L10

### An example. take a look  on  this  [Header.jsx file](https://github.com/devcbuea/dt-collect-web-client/blob/master/src/components/Header.jsx)
PullRight in line 14  and Navbar.Header line 9 is no more used in the recent react-bootstrap1.0.0-beta.8
https://github.com/devcbuea/dt-collect-web-client/blob/8911848cb14c433b57d9a8df8774de6f3b5acc8e/src/components/Header.jsx#L1-L22

### Another example. take a look  on  this  [LoginForm.jsx file](https://github.com/devcbuea/dt-collect-web-client/blob/master/src/containers/Login/LoginForm.jsx)
it imports ControlLabel (line 3) which is no more supported in this new version of react. The ControlLabel should be replaced with FormLabel when using the new version.
[Click this link for more info on react-bootstrap forms](https://react-bootstrap.github.io/components/forms/)
https://github.com/devcbuea/dt-collect-web-client/blob/8911848cb14c433b57d9a8df8774de6f3b5acc8e/src/containers/Login/LoginForm.jsx#L2-L5

 Therefore to avoid some unexpected problems when reading the documentation i proposed to change the package.json so that we use the most recent version of react-bootstrap and bootstrap and normalize  all the file using outdated features.

**Comment by Cressence** [comment]
Hey Arnold, This is the version we are using.. you can find documentation on that version online as well... 
If we update our react-bootstrap version, we will create tasks for it too.

**Comment by ArnolFokam** [comment]
Oh I see.  Can I have the link to the documentation of this version because I found it really hard to understand the codes with the documentation on the react-bootstrap website. Thanks

**Comment by Cressence** [comment]
https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/components/forms/
