### ISSUE TITLE
Conflicting css style rules

### ISSUE THREAD

**Issue by ArnolFokam** [devcbuea/dt-collect-web-client#32]
I found that the styles applied at the  `btn` class in  [Login.css](https://github.com/devcbuea/dt-collect-web-client/blob/master/src/containers/Login/Login.css)   could conflict with the styles of other buttons. I found the style in this button too specific and therefore could cause an unexpected behaviour when used for another type of button.
https://github.com/devcbuea/dt-collect-web-client/blob/8911848cb14c433b57d9a8df8774de6f3b5acc8e/src/containers/Login/Login.css#L31-L42
### An example.
the padding and the margin added on the btn class will not be suiable for the button of an inline form in a navigation bar.

A solution will be to change the class name of this btn. maybe to `btn-prettier` and assign it to all those buttons which needs this style and leave those `btn` class button which doesn't need it.

**Comment by Cressence** [comment]
Nice catch, thanks.
But this would be the default button shape of our buttons. 
I think a better thing to do would instead be to place that style in a general css file so that all buttons can use it directly

**Comment by ArnolFokam** [comment]
Yes of course. But honestly, I feel skeptical about using the `btn` class to style all our buttons.

**Comment by Cressence** [comment]
.btn  class will override the default bootstrap button... the buttons on the page should be consistent.. so for this project, that will be our default button

**Comment by ArnolFokam** [comment]
Oh i see.

**Comment by ArnolFokam** [comment]
And
